### ISSUE TITLE
GenRandomBits doesn't work correctly.

### ISSUE THREAD

**Issue by suddjian** [bazzilic/BigInteger#12]
GenRandomBits is broken. I'm not sure of all the specifics of this problem, and I'm still doing tests to try to figure it out. So far all I know is that on line 1542 the rembits value is used to create a mask which is OR'ed with the data. From tests I've run, if you call GenRandomBits with only 1 bit, you cannot get a 0 as a result. I'm sure this error exists in other cases as well, in fact I don't think it is possible to get a 0 as a result in any case.

**Comment by bazzilic** [comment]
Thank you for you post! I'll look into that and try to find the issue.

**Comment by bazzilic** [comment]
@ChemicalRocketeer `genRandomBits` was rewritten. The new version is not yet available via NuGet, but you can try the latest version from `master`. I close the issue, feel free to reopen or open a new one if there is anything wrong.
