### ISSUE TITLE
flag will always be false

### ISSUE THREAD

**Issue by jackmott** [bazzilic/BigInteger#25]
Saw this come up using PVS-Studio to do static analysis, not sure what the correct fix is though.

The flag boolean will always be false at this if statement:
https://github.com/bazzilic/BigInteger/blob/master/BigInteger/BigInteger.cs#L2897

**Comment by bazzilic** [comment]
After looking at the code - makes sense.

**Comment by jackmott** [comment]
Is there any underlying problem with the logic or can that if statement just be removed you think?

**Comment by bazzilic** [comment]
Hard to tell. We kind of "adopted" this library as it was abandoned by the original author and this particular code was written before. It is clear that the removing the if statement would not affect what the method does, however it is hard to tell if the method even works correctly. We don't test this method so we don't even know if it works at all :)
