### ISSUE TITLE
 Index was outside the bounds of the array exception, please help!

### ISSUE THREAD

**Issue by zhyy2008z** [bazzilic/BigInteger#26]
Please forgave my poor English! I calculate blow formula, it will throw exception: Index was outside the bounds of the array. I think there should be something wrong, such as length limit, please check it!

 new BigInteger(227404337504463).modPow(new BigInteger(new byte[] { 145, 1, 187, 185, 244, 27, 157, 89, 138, 28, 128, 102, 87, 114, 253, 96, 112, 39, 38, 229, 76, 238, 216, 214, 62, 193, 148, 20, 27, 4, 225, 148, 147, 173, 130, 218, 110, 209, 167, 252, 96, 140, 1, 197, 243, 243, 160, 243, 57, 63, 125, 75, 236, 199, 221, 153, 228, 163, 92, 14, 26, 82, 234, 99, 134, 164, 230, 155, 117, 176, 53, 9, 84, 133, 163, 203, 101, 143, 242, 216, 217, 212, 81, 133, 206, 155, 175, 97, 91, 157, 193, 144, 157, 46, 178, 152, 207, 212, 35, 58, 230, 255, 129, 40, 171, 212, 96, 192, 6, 0, 165, 36, 165, 183, 188, 10, 119, 44, 193, 128, 243, 177, 246, 2, 175, 149, 228, 164, 197, 15, 207, 83, 157, 186, 181, 90, 99, 46, 197, 198, 172, 106, 172, 130, 116, 241, 235, 184, 248, 11, 210, 83, 238, 234, 121, 60, 215, 227, 233, 72, 162, 15, 82, 14, 138, 198, 179, 54, 11, 239, 192, 170, 192, 236, 74, 33, 219, 97, 155, 121, 99, 105, 233, 137, 147, 225, 196, 149, 13, 22, 104, 58, 36, 12, 177, 115, 221, 110, 167, 54, 191, 240, 60, 24, 171, 147, 131, 173, 45, 137, 2, 177, 183, 73, 196, 166, 233, 166, 146, 64, 216, 49, 218, 162, 177, 37, 186, 0, 171, 127, 1, 51, 108, 114, 134, 79, 5, 82, 11, 39, 91, 78, 156, 100, 176, 73, 202, 228, 182, 102, 13, 208, 10, 154, 244, 233 }), new BigInteger(new byte[] { 165, 89, 134, 6, 110, 93, 43, 152, 4, 223, 129, 40, 74, 186, 185, 38, 45, 224, 85, 220, 102, 191, 247, 47, 129, 173, 174, 113, 65, 207, 129, 102, 145, 87, 46, 2, 242, 124, 132, 21, 170, 228, 30, 66, 246, 137, 149, 192, 235, 177, 44, 21, 190, 229, 139, 56, 18, 4, 176, 91, 82, 74, 140, 104, 41, 77, 22, 249, 239, 73, 81, 180, 159, 207, 202, 14, 52, 188, 19, 81, 33, 176, 18, 55, 219, 41, 94, 213, 149, 47, 67, 162, 80, 94, 73, 7, 87, 167, 91, 130, 239, 179, 17, 102, 26, 113, 218, 4, 55, 142, 60, 121, 206, 220, 244, 16, 76, 128, 109, 25, 126, 1, 15, 12, 147, 170, 246, 49, 52, 148, 218, 59, 42, 240, 131, 67, 31, 60, 42, 125, 60, 98, 6, 100, 187, 79, 163, 86, 25, 195, 42, 3, 17, 54, 7, 229, 56, 228, 60, 198, 151, 136, 37, 252, 21, 99, 181, 5, 232, 68, 76, 149, 40, 48, 61, 183, 187, 198, 184, 183, 40, 59, 67, 210, 46, 128, 191, 194, 117, 176, 212, 8, 149, 255, 7, 130, 133, 153, 181, 153, 87, 84, 43, 186, 153, 122, 202, 249, 4, 238, 8, 189, 19, 173, 159, 157, 207, 16, 103, 226, 46, 16, 25, 238, 108, 14, 249, 23, 133, 224, 13, 254, 242, 104, 22, 247, 46, 205, 189, 102, 138, 214, 53, 5, 18, 8, 193, 220, 103, 237, 94, 22, 76, 165, 200, 249 }));

**Comment by bazzilic** [comment]
Looks like you reach the size limit of this class (70*4 bytes). There are 2 things you can try:

1. Download the source for this class (it's just one file), add it to your project, change this line `private const int maxLength = 70;` to be larger. Try making it 200 or 500 to see whether it fixes the issue.

2. If you use .NET 4+, you can use `System.Numerics.BigInteger`. It doesn't have a `ModPow` method, but you can use my other class (BigIntegerExt, also available on nuget.org), which extends .NET BigInteger with some methods including ModPow.

**Comment by zhyy2008z** [comment]
I changed the maxLength field of BigInteger class to 140. Now, it works well, thanks a lot!

**Comment by bazzilic** [comment]
No problem!
