### ISSUE TITLE
Namespace?

### ISSUE THREAD

**Issue by picrap** [bazzilic/BigInteger#28]
Hi,

wouldn't it be better to place the class in a namespace? Currently, this causes conflicts with other classes named `BigInteger` (right, I'm using different classes with the same name, I'm a perv' 😉 )

Thank.

**Comment by bazzilic** [comment]
It definitely would be better, but this library is deprecated in favor of .NET System.Numerics implementation

**Comment by picrap** [comment]
... Which doesn't work on XP/2003 😢 
I'll try another lib, then. Thanks.

**Comment by bazzilic** [comment]
This library is just one C# file, you can download it and add to your project. There you can add the namespace, as well as change the size limit.
