### ISSUE TITLE
Why limiting integers size

### ISSUE THREAD

**Issue by picrap** [bazzilic/BigInteger#29]
Hi,

there is a size limit in the constructor (70 ints?).
Why is that?

Thanks.

**Comment by bazzilic** [comment]
I just took over the maintenance of the library, fixed a couple of bugs and uploaded a nuget package. The initial design choices are unknown to me, but I assume that this was done for simplicity of implementation. I actually considered making it variable size, but all operations rely on the array being the same size across different instances, so this would require rewriting _everything_.

**Comment by picrap** [comment]
OK, don't bother. Thanks!
