### ISSUE TITLE
Fix bug in the class constructor

### ISSUE THREAD

**Issue by bazzilic** [bazzilic/BigInteger#3]
There's a known bug in a class constructor. Need to research possible fixes and aply the best suitable one.

References:
1. http://www.codeproject.com/Messages/2853829/My-Fixes.aspx

**Comment by codelion** [comment]
I was just wondering since you are using it for a cryptography project that why not just use the implementation of arbitrary integers that is present in .NET (4.0 and above) - System.Numerics.BigInteger? Or http://biginteger.codeplex.com/ which works back till .NET 2.0.

**Comment by bazzilic** [comment]
There are a few reasons.

The BigInteger implementation from http://biginteger.codeplex.com/ is too basic and simplistic. It lacks many operations, e.g. `modPow` or even converting of the integer to a byte array.

There is a number of projects that are relying on this specific implementation of BigInteger (inlcuding some of my projects), so fixing its bugs is beneficial to many people.

`System.Numerics.BigInteger` is good in terms of provided functionality, however, it requires at least .NET 4.0 and is not directly compatible with this implementation (e.g., `.getBytes()` is in little endian whereas this implementation is big-endian).
