### ISSUE TITLE
Bug in Division and Modulo for negative numbers

### ISSUE THREAD

**Issue by furun** [bazzilic/BigInteger#30]
There are bugs in division and modulo for negative numbers.
I compared a test with Wolfram.

(The calculator in windows 7 is wrong too, I think...)

(Is the code still in development? I found more bugs and i would have some improvements.)

**Comment by bazzilic** [comment]
Can you share the test-cases that fail/give wrong result?
Also, this repo is no longer actively supported as there is a BigInteger class in .NET now.

**Comment by furun** [comment]
Result in BigInteger:
  0 == 31 / -1000
  0 == -31 / 1000
-32 == 1000 / -31
-32 == -1000 / 31
 31 == 31 % -1000
-31 == -31 % 1000
  8 == 1000 % -31
 -8 == -1000 % 31

This is OK:
  0 == -31 / -1000
 32 == -1000 / -31
-31 == -31 % -1000
 -8 == -1000 % -31


Result in Mathematica:
  -1 == Quotient[31, -1000]
  -1 == Quotient[-31, 1000]
 -33 == Quotient[1000, -31]
 -33 == Quotient[-1000, 31]
-969 == Mod[31, -1000]
 969 == Mod[-31, 1000]
 -23 == Mod[1000, -31]
  23 == Mod[-1000, 31]

This is OK:
   0 == Quotient[-31,-1000]
  32 == Quotient[-1000,-31]
 -31 == Mod[-31,-1000]
  -8 == Mod[-1000,-31]


Definition:
Floor[m/n] == Quotient[m,n]
Mod[m,n] == m - n * Quotient[m,n]

  -1 == Floor[31, -1000]
-969 == 31 - (-1000) * Quotient[31, -1000]


If you use this, it make sense:
https://www.wolframalpha.com/
Plot[Quotient[x,2],{x,-5,5}]
Plot[Mod[x,2],{x,-5,5}]

**Comment by furun** [comment]
Sorry for the delay. 
I had now some time to check the issue. I used Wolfram to check some of the basic functions, and foud out now that different software are using different rounding calculations.

This BigInteger code uses a round to 0 (like the native integer math),  mathematica uses round to floor, gmp supports all 3 variants including round to ceiling.

So it is not a bug, sorry for the inconvenience, this issue can be closed.
